"""Генераторы СИНТЕТИЧЕСКИХ DNA-fixture'ов для тестов.

Никаких реальных rsids/genotypes. Все random'ы детерминированы
через изолированный Random(seed=42), не трогают global state.
См. ADR-0012 §«Privacy guards в коде».
"""

from __future__ import annotations

import random

# 23andMe v5 raw header — цитата из их публичного формата, без
# genetic data, безопасно коммитить.
TWENTY_THREE_AND_ME_HEADER = (
    "# This data file generated by 23andMe at: Mon Jan  1 00:00:00 2024\n"
    "# This file contains raw genotype data, including data that is not used in "
    "23andMe reports.\n"
    "# This data has undergone a general quality review however only a subset of "
    "markers have been individually validated for accuracy.\n"
    "# More information on reference human assembly builds:\n"
    "#     GRCh37/hg19\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)

# Ancestry v2 raw header — те же соображения.
ANCESTRY_HEADER = (
    "#AncestryDNA Raw DNA Data Download\n"
    "#Data was generated by AncestryDNA on 01/01/2024.\n"
    "#Data is formatted using the AncestryDNA v2 format.\n"
    "#Reference build: 37\n"
    "#rsid\tchromosome\tposition\tallele1\tallele2\n"
)

_AUTOSOMAL_GENOTYPES = ("AA", "AC", "AG", "AT", "CC", "CG", "CT", "GG", "GT", "TT")


def _seeded_rng() -> random.Random:
    """Изолированный Random(seed=42), не для криптографии — детерминизм тестов."""
    return random.Random(42)


def generate_synthetic_23andme(num_snps: int = 100) -> str:
    """Синтетический 23andMe v5 raw файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["X", "Y", "MT"]
    parts = [TWENTY_THREE_AND_ME_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        # ~5% no-call для покрытия `--` ветки парсера.
        genotype = "--" if rng.random() < 0.05 else rng.choice(_AUTOSOMAL_GENOTYPES)
        parts.append(f"rs{i}\t{chrom}\t{pos}\t{genotype}\n")
    return "".join(parts)


def generate_synthetic_ancestry(num_snps: int = 100) -> str:
    """Синтетический Ancestry v2 raw файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["23", "24", "25"]
    parts = [ANCESTRY_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        if rng.random() < 0.05:
            allele1, allele2 = "0", "0"
        else:
            genotype = rng.choice(_AUTOSOMAL_GENOTYPES)
            allele1, allele2 = genotype[0], genotype[1]
        parts.append(f"rs{i}\t{chrom}\t{pos}\t{allele1}\t{allele2}\n")
    return "".join(parts)
