"""Генераторы СИНТЕТИЧЕСКИХ DNA-fixture'ов для тестов.

Никаких реальных rsids/genotypes. Все random'ы детерминированы
через изолированный Random(seed=42), не трогают global state.
См. ADR-0012 §«Privacy guards в коде».
"""

from __future__ import annotations

import random

# 23andMe v5 raw header — цитата из их публичного формата, без
# genetic data, безопасно коммитить.
TWENTY_THREE_AND_ME_HEADER = (
    "# This data file generated by 23andMe at: Mon Jan  1 00:00:00 2024\n"
    "# This file contains raw genotype data, including data that is not used in "
    "23andMe reports.\n"
    "# This data has undergone a general quality review however only a subset of "
    "markers have been individually validated for accuracy.\n"
    "# More information on reference human assembly builds:\n"
    "#     GRCh37/hg19\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)

# Ancestry v2 raw header — те же соображения.
ANCESTRY_HEADER = (
    "#AncestryDNA Raw DNA Data Download\n"
    "#Data was generated by AncestryDNA on 01/01/2024.\n"
    "#Data is formatted using the AncestryDNA v2 format.\n"
    "#Reference build: 37\n"
    "#rsid\tchromosome\tposition\tallele1\tallele2\n"
)

_AUTOSOMAL_GENOTYPES = ("AA", "AC", "AG", "AT", "CC", "CG", "CT", "GG", "GT", "TT")


# MyHeritage CSV header — цитата из их публичного формата, без genetic data.
MYHERITAGE_HEADER = (
    "# MyHeritage DNA raw data.\n"
    "# For each SNP, we provide the identifier, chromosome number,\n"
    "# base pair position and genotype.\n"
    "# The genotype is reported on the forward (+) strand with respect "
    "to the human reference build 37.\n"
    "RSID,CHROMOSOME,POSITION,RESULT\n"
)

# FTDNA Family Finder CSV header — без comment-блока, только CSV header line.
FTDNA_HEADER = "RSID,CHROMOSOME,POSITION,RESULT\n"

# LivingDNA raw TSV header — структурно копирует 23andMe (TSV, 4 колонки),
# отличается только signature-строкой. Цитата из публичного формата.
LIVING_DNA_HEADER = (
    "# LivingDNA Raw Data Download v1.0.0\n"
    "# Reference build: GRCh37 (hg19)\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)


def _seeded_rng() -> random.Random:
    """Изолированный Random(seed=42), не для криптографии — детерминизм тестов."""
    return random.Random(42)


def generate_synthetic_23andme(num_snps: int = 100) -> str:
    """Синтетический 23andMe v5 raw файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["X", "Y", "MT"]
    parts = [TWENTY_THREE_AND_ME_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        # ~5% no-call для покрытия `--` ветки парсера.
        genotype = "--" if rng.random() < 0.05 else rng.choice(_AUTOSOMAL_GENOTYPES)
        parts.append(f"rs{i}\t{chrom}\t{pos}\t{genotype}\n")
    return "".join(parts)


def generate_synthetic_ancestry(num_snps: int = 100) -> str:
    """Синтетический Ancestry v2 raw файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["23", "24", "25"]
    parts = [ANCESTRY_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        if rng.random() < 0.05:
            allele1, allele2 = "0", "0"
        else:
            genotype = rng.choice(_AUTOSOMAL_GENOTYPES)
            allele1, allele2 = genotype[0], genotype[1]
        parts.append(f"rs{i}\t{chrom}\t{pos}\t{allele1}\t{allele2}\n")
    return "".join(parts)


def generate_synthetic_myheritage(num_snps: int = 100) -> str:
    """Синтетический MyHeritage raw CSV файл с N SNP-ами (детерминированный).

    Использует quoted CSV (как в реальных MyHeritage-экспортах). Default build
    в header — GRCh37; для отдельных тестов на build detection см. ad-hoc
    fixtures внутри test_myheritage.py.
    """
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["X", "Y", "MT"]
    parts = [MYHERITAGE_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        genotype = "--" if rng.random() < 0.05 else rng.choice(_AUTOSOMAL_GENOTYPES)
        parts.append(f'"rs{i}","{chrom}","{pos}","{genotype}"\n')
    return "".join(parts)


def generate_synthetic_ftdna(num_snps: int = 100) -> str:
    """Синтетический FTDNA Family Finder raw CSV файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["X", "Y", "MT"]
    parts = [FTDNA_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        genotype = "--" if rng.random() < 0.05 else rng.choice(_AUTOSOMAL_GENOTYPES)
        parts.append(f'"rs{i}","{chrom}","{pos}","{genotype}"\n')
    return "".join(parts)


def generate_synthetic_livingdna(num_snps: int = 100) -> str:
    """Синтетический LivingDNA raw TSV файл с N SNP-ами (детерминированный)."""
    rng = _seeded_rng()
    chromosomes = [str(c) for c in range(1, 23)] + ["X", "Y", "MT"]
    parts = [LIVING_DNA_HEADER]
    for i in range(1, num_snps + 1):
        chrom = rng.choice(chromosomes)
        pos = rng.randint(1_000_000, 250_000_000)
        genotype = "--" if rng.random() < 0.05 else rng.choice(_AUTOSOMAL_GENOTYPES)
        parts.append(f"rs{i}\t{chrom}\t{pos}\t{genotype}\n")
    return "".join(parts)
