"""End-to-end тесты CLI `dna-analysis match`.

Использует click.testing.CliRunner — НЕ запускает subprocess, так что
работает в любой CI-среде. Все DNA-файлы — синтетические fixture'ы из
Phase 6.0 (tests/fixtures/synthetic_*.txt) и/или построенные на лету
из tests/matching/_simulators.py.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

import pytest
from click.testing import CliRunner
from dna_analysis.cli import cli

from tests.matching._simulators import simulate_parent_child_pair


def _write_23andme_file(tmp_path: Path, content: str) -> Path:
    path = tmp_path / "test_23andme.txt"
    path.write_text(content, encoding="utf-8")
    return path


def _write_ancestry_file(tmp_path: Path, content: str) -> Path:
    path = tmp_path / "test_ancestry.txt"
    path.write_text(content, encoding="utf-8")
    return path


def _serialize_test_to_23andme(test) -> str:
    """Сериализует DnaTest назад в 23andMe raw формат для сквозного теста."""
    lines = [
        "# This data file generated by 23andMe at: Mon Jan  1 00:00:00 2024\n",
        "# rsid\tchromosome\tposition\tgenotype\n",
    ]
    for snp in test.snps:
        chr_token = (
            "X"
            if int(snp.chromosome) == 23
            else (
                "Y"
                if int(snp.chromosome) == 24
                else ("MT" if int(snp.chromosome) == 25 else str(int(snp.chromosome)))
            )
        )
        lines.append(f"{snp.rsid}\t{chr_token}\t{snp.position}\t{snp.genotype.value}\n")
    return "".join(lines)


def _serialize_test_to_ancestry(test) -> str:
    """Сериализует DnaTest назад в Ancestry v2 raw формат."""
    lines = [
        "#AncestryDNA Raw DNA Data Download\n",
        "#rsid\tchromosome\tposition\tallele1\tallele2\n",
    ]
    for snp in test.snps:
        gt = snp.genotype.value
        if gt == "NN":
            a1, a2 = "0", "0"
        elif len(gt) == 2:
            a1, a2 = gt[0], gt[1]
        else:
            # hemizygous (single allele) — Ancestry формат не использует;
            # дублируем для simplicity.
            a1 = a2 = gt[0]
        lines.append(f"{snp.rsid}\t{int(snp.chromosome)}\t{snp.position}\t{a1}\t{a2}\n")
    return "".join(lines)


@pytest.fixture
def genetic_map_dir(fixtures_dir: Path) -> Path:
    return fixtures_dir / "genetic_map"


@pytest.fixture
def parent_child_files(tmp_path: Path) -> tuple[Path, Path]:
    parent, child = simulate_parent_child_pair(num_snps=2_500)
    file_a = _write_23andme_file(tmp_path, _serialize_test_to_23andme(parent))
    file_b = _write_ancestry_file(tmp_path, _serialize_test_to_ancestry(child))
    return file_a, file_b


def test_match_outputs_valid_json(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    assert result.exit_code == 0, result.output
    data = json.loads(result.output)

    assert set(data.keys()) == {
        "test_a",
        "test_b",
        "shared_segments",
        "total_shared_cm",
        "longest_segment_cm",
        "relationship_predictions",
        "warnings",
    }


def test_match_summarizes_both_tests(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)

    assert data["test_a"]["provider"] == "23andme"
    assert data["test_b"]["provider"] == "ancestry"
    assert data["test_a"]["snp_count"] == 2_500
    assert data["test_b"]["snp_count"] == 2_500
    assert data["test_a"]["reference_build"] == "GRCh37"


def test_match_yields_full_chromosome_segment_for_parent_child(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)

    # Parent-child на chr22 → один сегмент через всю хромосому.
    assert len(data["shared_segments"]) >= 1
    seg = data["shared_segments"][0]
    assert seg["chromosome"] == 22
    assert seg["num_snps"] >= 2_000  # ≈ все SNP минус no-call вкрапления
    assert seg["cm_length"] >= 30
    assert data["total_shared_cm"] > 30
    assert data["longest_segment_cm"] > 30


def test_match_includes_relationship_predictions(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)

    preds = data["relationship_predictions"]
    assert isinstance(preds, list)
    assert all("label" in p and "probability" in p and "cm_range" in p for p in preds)
    # Source attribution должен быть в каждом prediction.
    assert all("Shared cM Project" in p["source"] for p in preds)


def test_match_emits_cross_platform_warning(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)

    assert any("Cross-platform" in w for w in data["warnings"])


def test_match_no_warning_for_same_platform(tmp_path: Path, genetic_map_dir: Path) -> None:
    parent, child = simulate_parent_child_pair(num_snps=2_000)
    file_a = tmp_path / "a.txt"
    file_b = tmp_path / "b.txt"
    file_a.write_text(_serialize_test_to_23andme(parent), encoding="utf-8")
    file_b.write_text(_serialize_test_to_23andme(child), encoding="utf-8")

    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)
    assert not any("Cross-platform" in w for w in data["warnings"])


def test_match_segments_have_no_raw_genotype_data(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    """Privacy: сегменты в JSON содержат только bp/cM/count, не SNP-кalls."""
    file_a, file_b = parent_child_files
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    data = json.loads(result.output)

    for seg in data["shared_segments"]:
        assert set(seg.keys()) == {"chromosome", "start_bp", "end_bp", "num_snps", "cm_length"}
        # Не должно быть полей вроде "rsids" или "genotypes".
        assert "rsids" not in seg
        assert "genotypes" not in seg


def test_match_does_not_log_raw_values(
    parent_child_files: tuple[Path, Path],
    genetic_map_dir: Path,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """Privacy guard: логи end-to-end pipeline не содержат raw values."""
    file_a, file_b = parent_child_files
    runner = CliRunner()
    with caplog.at_level(logging.DEBUG):
        runner.invoke(
            cli,
            ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
        )

    log_text = "\n".join(record.message for record in caplog.records)
    # Не должно быть rsid (rs1, rs2, ...).
    assert not re.search(r"\brs\d+\b", log_text), f"rsid leaked: {log_text!r}"
    # Не должно быть position-like чисел (8+-digit).
    assert not re.search(r"\b\d{8,}\b", log_text), f"position leaked: {log_text!r}"


def test_match_rejects_unknown_format(tmp_path: Path, genetic_map_dir: Path) -> None:
    file_a = tmp_path / "weird.txt"
    file_a.write_text("not a real DNA file\n", encoding="utf-8")
    parent, _ = simulate_parent_child_pair(num_snps=500)
    file_b = tmp_path / "ok.txt"
    file_b.write_text(_serialize_test_to_23andme(parent), encoding="utf-8")

    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["match", str(file_a), str(file_b), "--genetic-map", str(genetic_map_dir)],
    )
    assert result.exit_code != 0
    assert isinstance(result.exception, Exception)


def test_match_requires_existing_input_files(tmp_path: Path, genetic_map_dir: Path) -> None:
    runner = CliRunner()
    result = runner.invoke(
        cli,
        [
            "match",
            str(tmp_path / "missing.txt"),
            str(tmp_path / "missing2.txt"),
            "--genetic-map",
            str(genetic_map_dir),
        ],
    )
    assert result.exit_code != 0
    assert "does not exist" in result.output.lower() or "no such" in result.output.lower()


def test_min_cm_and_min_snps_options_propagate(
    parent_child_files: tuple[Path, Path], genetic_map_dir: Path
) -> None:
    """Custom thresholds меняют размер результата."""
    file_a, file_b = parent_child_files
    runner = CliRunner()
    # Очень высокий min_cm должен убрать сегмент целиком.
    result = runner.invoke(
        cli,
        [
            "match",
            str(file_a),
            str(file_b),
            "--genetic-map",
            str(genetic_map_dir),
            "--min-cm",
            "100.0",
        ],
    )
    data = json.loads(result.output)
    assert data["shared_segments"] == []
    assert data["total_shared_cm"] == 0


def test_cli_help_shows_match_command() -> None:
    runner = CliRunner()
    result = runner.invoke(cli, ["--help"])
    assert result.exit_code == 0
    assert "match" in result.output.lower()
