"""Тесты универсального диспетчера парсинга raw DNA-файлов.

`parse_raw(content)` должен:
1. Корректно роутить каждый из 5 форматов в соответствующий парсер.
2. Возвращать `DnaTest` (alias `ParseResult`).
3. Бросать `UnsupportedFormatError` на нераспознанном тексте.
4. Пробрасывать `DnaParseError` из парсера, если формат распознан, но
   содержимое битое.
"""

from __future__ import annotations

import pytest
from dna_analysis import (
    DnaParseError,
    DnaTest,
    ParseResult,
    Provider,
    UnsupportedFormatError,
    parse_raw,
)


def test_dispatches_23andme(synthetic_23andme_file: str) -> None:
    test = parse_raw(synthetic_23andme_file)
    assert test.provider is Provider.TWENTY_THREE_AND_ME


def test_dispatches_ancestry(synthetic_ancestry_file: str) -> None:
    test = parse_raw(synthetic_ancestry_file)
    assert test.provider is Provider.ANCESTRY


def test_dispatches_myheritage(synthetic_myheritage_file: str) -> None:
    test = parse_raw(synthetic_myheritage_file)
    assert test.provider is Provider.MYHERITAGE


def test_dispatches_ftdna(synthetic_ftdna_file: str) -> None:
    test = parse_raw(synthetic_ftdna_file)
    assert test.provider is Provider.FTDNA


def test_dispatches_livingdna(synthetic_livingdna_file: str) -> None:
    test = parse_raw(synthetic_livingdna_file)
    assert test.provider is Provider.LIVING_DNA


def test_returns_dnatest_aliased_as_parseresult(synthetic_23andme_file: str) -> None:
    """ParseResult — back-compat alias на DnaTest. parse_raw возвращает оба имени."""
    result = parse_raw(synthetic_23andme_file)
    assert isinstance(result, DnaTest)
    assert isinstance(result, ParseResult)
    assert ParseResult is DnaTest


def test_raises_unsupported_for_random_text() -> None:
    with pytest.raises(UnsupportedFormatError, match="not recognized"):
        parse_raw("hello world\nthis is not DNA\n")


def test_raises_unsupported_for_empty_content() -> None:
    with pytest.raises(UnsupportedFormatError):
        parse_raw("")


def test_propagates_parse_error_for_recognized_but_broken_content() -> None:
    """Если detect-сигнатура нашлась, но строки битые — `DnaParseError` из парсера."""
    broken_23andme = (
        "# This data file generated by 23andMe at: Mon Jan  1 00:00:00 2024\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t99\t12345\tAA\n"  # invalid chromosome
    )
    with pytest.raises(DnaParseError):
        parse_raw(broken_23andme)


def test_myheritage_takes_priority_over_ftdna_on_overlapping_csv_header() -> None:
    """Файл с `# MyHeritage` блоком + общим CSV header → MyHeritage, не FTDNA.

    Регрессионная защита от ошибки порядка probe'ов в _PARSER_REGISTRY.
    """
    content = '# MyHeritage DNA raw data.\nRSID,CHROMOSOME,POSITION,RESULT\n"rs1","1","100","AA"\n'
    test = parse_raw(content)
    assert test.provider is Provider.MYHERITAGE
