"""Универсальный диспетчер парсинга raw DNA-файлов по содержимому.

`parse_raw(content)` — единая точка входа для downstream consumers
(Phase 16.2 dna-painter, Phase 6.x dna-service). Probes каждый
зарегистрированный парсер через его `detect()` и делегирует первому,
который распознал формат.

Порядок probe'ов:
1. AncestryDNA — `#AncestryDNA Raw DNA Data` (специфичная сигнатура).
2. 23andMe — `# This data file generated by 23andMe`.
3. MyHeritage — `# MyHeritage DNA raw data`.
4. LivingDNA — `# LivingDNA`.
5. FamilyTreeDNA — column-header `RSID,CHROMOSOME,POSITION,RESULT` без `#`-блока.
   Идёт последним: его detection-строка пересекается с MyHeritage'овской
   column-header строкой, поэтому MyHeritage detect() (специфичный
   `# MyHeritage` маркер) обязан выстрелить раньше.

Каждый парсер pure — диспетчер не делает ни IO, ни сетевых вызовов.
"""

from __future__ import annotations

from typing import Final

from dna_analysis.errors import UnsupportedFormatError
from dna_analysis.models import DnaTest
from dna_analysis.parsers import (
    AncestryParser,
    BaseDnaParser,
    FamilyTreeDnaParser,
    LivingDnaParser,
    MyHeritageParser,
    TwentyThreeAndMeParser,
)

# Порядок важен: MyHeritage обязан probe-аться раньше FTDNA (см. модуль-docstring).
_PARSER_REGISTRY: Final[tuple[type[BaseDnaParser], ...]] = (
    AncestryParser,
    TwentyThreeAndMeParser,
    MyHeritageParser,
    LivingDnaParser,
    FamilyTreeDnaParser,
)


def parse_raw(content: str) -> DnaTest:
    """Парсит raw DNA-файл, автоматически определяя провайдера по содержимому.

    Args:
        content: Текст файла (UTF-8 decoded). Decoding выполняет caller —
            здесь работаем со str.

    Returns:
        DnaTest с распарсенными SNP и метаданными провайдера.

    Raises:
        UnsupportedFormatError: Если ни один зарегистрированный парсер не
            распознал формат файла.
        DnaParseError: Если формат распознан, но содержимое не парсится
            (пробрасывается из выбранного парсера).
    """
    for parser_cls in _PARSER_REGISTRY:
        if parser_cls.detect(content):
            return parser_cls().parse(content)

    msg = "raw DNA file format not recognized by any registered parser"
    raise UnsupportedFormatError(msg)
