"""Парсер AncestryDNA v2 raw данных.

Формат документирован Ancestry в header'е каждого экспорта:
    #AncestryDNA Raw DNA Data Download
    #Data was generated by AncestryDNA on ...
    #rsid\tchromosome\tposition\tallele1\tallele2
    rs4477212\t1\t82154\tA\tA
    ...

Reference build для v2 — GRCh37 (Build 37 / hg19), фиксирован.
В отличие от 23andMe, Ancestry разделяет два аллеля на отдельные
колонки и кодирует X/Y/MT как 23/24/25.

Приватность (см. ADR-0012):
- В логах — только агрегаты (количество SNP, prefix sha256-хеша файла).
- DnaParseError содержит line number и тип ошибки, но НЕ raw value.
"""

from __future__ import annotations

import hashlib
import logging
from typing import Final

from dna_analysis.errors import DnaParseError, UnsupportedFormatError
from dna_analysis.models import Chromosome, DnaTest, Genotype, Provider, ReferenceBuild
from dna_analysis.parsers.base import BaseDnaParser

_LOG: Final = logging.getLogger(__name__)

_DETECT_SIGNATURE: Final = "AncestryDNA Raw DNA Data"
_DETECT_HEAD_LINES: Final = 20

_REFERENCE_BUILD: Final = ReferenceBuild.GRCH37
_VERSION: Final = "v2"

# Ancestry кодирует X=23, Y=24, MT=25 как numeric строки.
# Аутосомы 1..22 — те же численные значения, что и Chromosome.CHR_*.
_CHROMOSOME_MAP: Final[dict[str, Chromosome]] = {str(i): Chromosome(i) for i in range(1, 26)}

# Каждый аллель — A/C/G/T или 0 (no-call). Diploid genotype = allele1 + allele2,
# нормализуется в Genotype enum (lex-sorted для гетерозигот).
_VALID_ALLELES: Final = frozenset("ACGT")
_NO_CALL_ALLELE: Final = "0"

_HOMOZYGOUS_GENOTYPE: Final[dict[str, Genotype]] = {
    "AA": Genotype.AA,
    "CC": Genotype.CC,
    "GG": Genotype.GG,
    "TT": Genotype.TT,
}

# Гетерозиготы — нормализуем сортировкой пары: {A,C} → AC независимо от порядка.
_HETEROZYGOUS_GENOTYPE: Final[dict[str, Genotype]] = {
    "AC": Genotype.AC,
    "AG": Genotype.AG,
    "AT": Genotype.AT,
    "CG": Genotype.CG,
    "CT": Genotype.CT,
    "GT": Genotype.GT,
}

_EXPECTED_COLUMN_COUNT: Final = 5


class AncestryParser(BaseDnaParser):
    """Парсер AncestryDNA v2 raw TSV (GRCh37, 5 columns: rsid, chr, pos, a1, a2)."""

    @classmethod
    def detect(cls, content: str) -> bool:
        """True, если в первых _DETECT_HEAD_LINES строках есть header-сигнатура."""
        for i, line in enumerate(content.splitlines()):
            if i >= _DETECT_HEAD_LINES:
                return False
            if _DETECT_SIGNATURE in line:
                return True
        return False

    def parse(self, content: str) -> DnaTest:
        if not self.detect(content):
            msg = "content does not look like an AncestryDNA v2 raw file"
            raise UnsupportedFormatError(msg)

        snps: list[dict[str, object]] = []
        for line_idx, raw_line in enumerate(content.splitlines(), start=1):
            line = raw_line.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            snps.append(_parse_snp_row(line, line_idx))

        if not snps:
            msg = "no SNP rows found after header"
            raise DnaParseError(msg)

        # SHA-256 prefix для logging — privacy-safe идентификатор файла.
        file_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()[:8]
        _LOG.debug("parsed %d SNPs from AncestryDNA file [%s]", len(snps), file_hash)

        return DnaTest(
            provider=Provider.ANCESTRY,
            version=_VERSION,
            reference_build=_REFERENCE_BUILD,
            snps=snps,
        )


def _combine_alleles(allele1: str, allele2: str) -> Genotype | None:
    """Соединяет два allele-токена в Genotype или возвращает None при невалиде.

    Логика:
      - "0" + "0" → no-call (NN). Только один из аллелей "0" — невалид
        (Ancestry экспортирует либо оба, либо ни одного).
      - Гомозиготы (AA/CC/GG/TT) — прямое соответствие.
      - Гетерозиготы — sortируем пару, lookup'имся в _HETEROZYGOUS_GENOTYPE.
    """
    if allele1 == _NO_CALL_ALLELE and allele2 == _NO_CALL_ALLELE:
        return Genotype.NN
    if _NO_CALL_ALLELE in (allele1, allele2):
        # Половинный no-call — Ancestry так не экспортирует, считаем ошибкой.
        return None
    if allele1 not in _VALID_ALLELES or allele2 not in _VALID_ALLELES:
        return None

    if allele1 == allele2:
        return _HOMOZYGOUS_GENOTYPE.get(allele1 + allele2)

    # Гетерозигота — отсортировать пару для канонической формы.
    pair = "".join(sorted([allele1, allele2]))
    return _HETEROZYGOUS_GENOTYPE.get(pair)


def _parse_snp_row(line: str, line_number: int) -> dict[str, object]:
    """Парсит одну SNP-строку Ancestry TSV в kwargs для Snp(...)."""
    parts = line.split("\t")
    if len(parts) != _EXPECTED_COLUMN_COUNT:
        msg = f"expected {_EXPECTED_COLUMN_COUNT} tab-separated columns, got {len(parts)}"
        raise DnaParseError(msg, line_number=line_number)

    rsid, chrom_token, position_token, allele1, allele2 = parts

    if not rsid:
        msg = "empty rsid"
        raise DnaParseError(msg, line_number=line_number)

    chromosome = _CHROMOSOME_MAP.get(chrom_token)
    if chromosome is None:
        msg = "invalid chromosome"
        raise DnaParseError(msg, line_number=line_number)

    try:
        position = int(position_token)
    except ValueError as exc:
        msg = "invalid position (not an integer)"
        raise DnaParseError(msg, line_number=line_number) from exc
    if position <= 0:
        msg = "invalid position (must be positive)"
        raise DnaParseError(msg, line_number=line_number)

    genotype = _combine_alleles(allele1, allele2)
    if genotype is None:
        msg = "invalid allele pair"
        raise DnaParseError(msg, line_number=line_number)

    return {
        "rsid": rsid,
        "chromosome": chromosome,
        "position": position,
        "genotype": genotype,
    }
