"""Тесты парсера 23andMe v5.

Все fixture-данные синтетические (см. tests/_generators.py +
tests/fixtures/synthetic_23andme.txt). Никаких реальных rsids/genotypes.
"""

from __future__ import annotations

import logging
import re

import pytest
from dna_analysis import (
    Chromosome,
    DnaParseError,
    DnaTest,
    Genotype,
    Provider,
    ReferenceBuild,
    UnsupportedFormatError,
)
from dna_analysis.parsers import TwentyThreeAndMeParser


def test_parser_detects_23andme_format(synthetic_23andme_file: str) -> None:
    assert TwentyThreeAndMeParser.detect(synthetic_23andme_file) is True


def test_parser_rejects_unknown_format() -> None:
    assert TwentyThreeAndMeParser.detect("hello\nthis is plain text\n") is False


def test_parser_does_not_match_ancestry_header(synthetic_ancestry_file: str) -> None:
    assert TwentyThreeAndMeParser.detect(synthetic_ancestry_file) is False


def test_parser_parses_synthetic_file(synthetic_23andme_file: str) -> None:
    parser = TwentyThreeAndMeParser()
    test = parser.parse(synthetic_23andme_file)

    assert isinstance(test, DnaTest)
    assert test.provider is Provider.TWENTY_THREE_AND_ME
    assert test.version == "v5"
    assert test.reference_build is ReferenceBuild.GRCH37
    assert len(test.snps) == 100  # synthetic generator выдаёт 100 SNP


def test_parser_skips_comment_lines(synthetic_23andme_file: str) -> None:
    """Header-комментарии (# ...) не должны попадать в snps."""
    parser = TwentyThreeAndMeParser()
    test = parser.parse(synthetic_23andme_file)

    # Все rsid должны соответствовать pattern rs1..rs100, не комментарию.
    for snp in test.snps:
        assert re.fullmatch(r"rs\d+", snp.rsid), f"unexpected rsid {snp.rsid!r}"


def test_parser_handles_no_call_genotype() -> None:
    """`--` от 23andMe нормализуется в Genotype.NN."""
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t12345\t--\n"
    )
    parser = TwentyThreeAndMeParser()
    test = parser.parse(content)

    assert len(test.snps) == 1
    assert test.snps[0].genotype is Genotype.NN


def test_parser_handles_x_y_mt_chromosomes() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\tX\t100\tAA\n"
        "rs2\tY\t200\tA\n"
        "rs3\tMT\t300\tC\n"
    )
    parser = TwentyThreeAndMeParser()
    test = parser.parse(content)

    chromosomes = [snp.chromosome for snp in test.snps]
    assert chromosomes == [Chromosome.X, Chromosome.Y, Chromosome.MT]


def test_parser_normalizes_heterozygous_pair_order() -> None:
    """`CA` от 23andMe должен нормализоваться в Genotype.AC."""
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t100\tCA\n"
        "rs2\t1\t200\tTG\n"
    )
    parser = TwentyThreeAndMeParser()
    test = parser.parse(content)

    assert test.snps[0].genotype is Genotype.AC
    assert test.snps[1].genotype is Genotype.GT


def test_parser_rejects_invalid_chromosome() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t99\t12345\tAA\n"
    )
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError) as exc:
        parser.parse(content)
    assert exc.value.line_number == 3
    assert "chromosome" in str(exc.value).lower()
    # Privacy: сырое значение "99" НЕ должно быть в сообщении.
    assert "99" not in str(exc.value)


def test_parser_rejects_unknown_genotype() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t12345\tZZ\n"
    )
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError) as exc:
        parser.parse(content)
    assert exc.value.line_number == 3
    assert "genotype" in str(exc.value).lower()
    # Privacy: сырое значение "ZZ" НЕ должно быть в сообщении.
    assert "ZZ" not in str(exc.value)


def test_parser_rejects_non_integer_position() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\tnot_a_number\tAA\n"
    )
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError) as exc:
        parser.parse(content)
    assert exc.value.line_number == 3


def test_parser_rejects_zero_position() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t0\tAA\n"
    )
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError) as exc:
        parser.parse(content)
    assert exc.value.line_number == 3


def test_parser_rejects_wrong_column_count() -> None:
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t12345\n"  # 3 колонки вместо 4
    )
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError) as exc:
        parser.parse(content)
    assert exc.value.line_number == 3


def test_parser_rejects_file_with_no_data_rows() -> None:
    content = "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n"
    parser = TwentyThreeAndMeParser()
    with pytest.raises(DnaParseError, match="no SNP rows"):
        parser.parse(content)


def test_parse_raises_unsupported_for_non_23andme_content() -> None:
    parser = TwentyThreeAndMeParser()
    with pytest.raises(UnsupportedFormatError):
        parser.parse("not a 23andMe file at all\nrandom text\n")


def test_parser_does_not_log_raw_values(
    synthetic_23andme_file: str,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """Privacy guard: парсер не должен логировать rsid/genotype/position SNP."""
    parser = TwentyThreeAndMeParser()
    with caplog.at_level(logging.DEBUG, logger="dna_analysis.parsers.twentythreeand_me"):
        parser.parse(synthetic_23andme_file)

    log_text = "\n".join(record.message for record in caplog.records)
    # Не должно быть rsid (например `rs42`) — даже от синтетических.
    assert not re.search(r"\brs\d+\b", log_text), f"rsid leaked into logs: {log_text!r}"
    # Не должно быть genotype-токенов.
    for token in ("AA", "AC", "AG", "AT", "CC", "CG", "CT", "GG", "GT", "TT", "--"):
        assert token not in log_text, f"genotype {token!r} leaked into logs: {log_text!r}"
