"""i18n строки для Court-Ready Report (en + ru).

Hardcoded mapping вместо подключения next-intl / babel — отчёт это
backend-render, не shared с frontend bundle. Расширение на новые
locale = новая запись в ``_STRINGS``.
"""

from __future__ import annotations

from typing import Final, Literal, cast

from parser_service.court_ready.models import ReportLocale

# event_type → human-readable label. Ключи — GEDCOM event types
# (BIRT, DEAT, MARR, ...) + наши custom event-tags.
_EVENT_LABELS: Final[dict[str, dict[ReportLocale, str]]] = {
    "BIRT": {"en": "Birth", "ru": "Рождение"},
    "DEAT": {"en": "Death", "ru": "Смерть"},
    "MARR": {"en": "Marriage", "ru": "Брак"},
    "DIV": {"en": "Divorce", "ru": "Развод"},
    "BAPM": {"en": "Baptism", "ru": "Крещение"},
    "BURI": {"en": "Burial", "ru": "Погребение"},
    "RESI": {"en": "Residence", "ru": "Место жительства"},
    "OCCU": {"en": "Occupation", "ru": "Род занятий"},
    "EMIG": {"en": "Emigration", "ru": "Эмиграция"},
    "IMMI": {"en": "Immigration", "ru": "Иммиграция"},
    "NATU": {"en": "Naturalization", "ru": "Натурализация"},
    "CENS": {"en": "Census", "ru": "Перепись"},
    "EDUC": {"en": "Education", "ru": "Образование"},
    "MILT": {"en": "Military service", "ru": "Военная служба"},
    "ENGA": {"en": "Engagement", "ru": "Помолвка"},
    "ANUL": {"en": "Annulment", "ru": "Аннулирование брака"},
    "ADOP": {"en": "Adoption", "ru": "Усыновление"},
    "EVEN": {"en": "Event", "ru": "Событие"},
    "CUSTOM": {"en": "Event", "ru": "Событие"},
}


# Все остальные UI-фразы.
_STRINGS: Final[dict[str, dict[ReportLocale, str]]] = {
    "report_title": {
        "en": "Court-Ready Genealogical Report",
        "ru": "Генеалогический отчёт со ссылками на источники",
    },
    "subject": {"en": "Subject", "ru": "Субъект"},
    "generated_at": {"en": "Generated", "ru": "Дата формирования"},
    "generated_by": {"en": "Generated by", "ru": "Подготовлено"},
    "subject_summary": {"en": "Subject summary", "ru": "Сводка по субъекту"},
    "family_relationships": {"en": "Family relationships", "ru": "Семейные связи"},
    "evidence_trail": {"en": "Evidence trail", "ru": "Доказательная цепочка"},
    "negative_findings": {"en": "Negative findings", "ru": "Отрицательные результаты"},
    "ancestry": {"en": "Ancestry", "ru": "Линия предков"},
    "signature_page": {"en": "Signature & methodology", "ru": "Подпись и методология"},
    "researcher": {"en": "Researcher", "ru": "Исследователь"},
    "methodology": {"en": "Methodology", "ru": "Методология"},
    "scope": {"en": "Scope", "ru": "Объём"},
    "tree": {"en": "Tree", "ru": "Дерево"},
    "primary_name": {"en": "Primary name", "ru": "Основное имя"},
    "also_known_as": {"en": "Also known as", "ru": "Также известен как"},
    "sex": {"en": "Sex", "ru": "Пол"},
    "birth": {"en": "Birth", "ru": "Рождение"},
    "death": {"en": "Death", "ru": "Смерть"},
    "no_records_found": {"en": "No records found", "ru": "Записи не найдены"},
    "claim": {"en": "Claim", "ru": "Утверждение"},
    "source": {"en": "Source", "ru": "Источник"},
    "confidence": {"en": "Confidence", "ru": "Достоверность"},
    "evidence_type": {"en": "Evidence type", "ru": "Тип доказательства"},
    "kind_citation": {"en": "Direct citation", "ru": "Прямая цитата"},
    "kind_inference_rule": {"en": "Inference rule", "ru": "Логическое правило"},
    "kind_asserted_only": {"en": "Asserted only", "ru": "Только заявлено"},
    "method_bayesian": {"en": "Bayesian fusion v2", "ru": "Байесовская агрегация v2"},
    "method_naive": {"en": "Naive count", "ru": "Простой счёт"},
    "method_asserted": {"en": "Not evaluated", "ru": "Не оценивалось"},
    "relation_parent": {"en": "Parent", "ru": "Родитель"},
    "relation_child": {"en": "Child", "ru": "Ребёнок"},
    "relation_spouse": {"en": "Spouse", "ru": "Супруг(а)"},
    "relation_sibling": {"en": "Sibling", "ru": "Брат/Сестра"},
    "footnote_label": {"en": "Footnote", "ru": "Сноска"},
    "page": {"en": "page", "ru": "стр."},
    "quality_label": {"en": "quality", "ru": "качество"},
    "no_relationships": {"en": "No relationships recorded.", "ru": "Связи не зафиксированы."},
    "no_negative_findings": {
        "en": "No gaps detected — every recorded fact has at least one source.",
        "ru": "Пробелы не выявлены — каждое утверждение подкреплено как минимум одним источником.",
    },
    "negative_kind_event_without_source": {
        "en": "Event without source",
        "ru": "Событие без источника",
    },
    "negative_kind_relationship_without_evidence": {
        "en": "Relationship without evidence",
        "ru": "Связь без доказательств",
    },
    "negative_kind_missing_vital": {
        "en": "Missing vital record",
        "ru": "Отсутствует ключевая запись",
    },
    "ancestry_generation": {"en": "Generation", "ru": "Поколение"},
    "scope_person": {"en": "Single person", "ru": "Одна персона"},
    "scope_family": {"en": "Family unit", "ru": "Семья"},
    "scope_ancestry_to_gen": {
        "en": "Ancestry up to generation {n}",
        "ru": "Линия предков до поколения {n}",
    },
    "default_methodology": {
        "en": (
            "This report aggregates GEDCOM facts and external citations stored in the "
            "subject's tree. Each claim is linked to its primary source(s) by footnote. "
            "Confidence scores are derived from GEDCOM QUAY values (where present) and "
            "from the inference engine's Bayesian fusion (ADR-0058) where multiple "
            "evidence streams converge. Gaps and unsupported assertions are listed in "
            "the Negative findings section so they can be addressed by additional "
            "research before any legal or heritage submission."
        ),
        "ru": (
            "Отчёт агрегирует факты из GEDCOM и внешние цитаты, сохранённые в дереве "
            "субъекта. Каждое утверждение связано с первичным источником через сноску. "
            "Оценки достоверности выводятся из значений GEDCOM QUAY (если заданы) и "
            "из байесовской агрегации движка гипотез (ADR-0058) при наличии нескольких "
            "потоков доказательств. Пробелы и неподкреплённые утверждения перечислены "
            "в секции «Отрицательные результаты», чтобы их можно было устранить перед "
            "юридической или архивной подачей."
        ),
    },
    "footnotes": {"en": "Footnotes", "ru": "Сноски"},
    "no_birth": {"en": "Not recorded", "ru": "Не зафиксировано"},
    "no_death": {"en": "Not recorded", "ru": "Не зафиксировано"},
    "unknown_sex": {"en": "Unknown", "ru": "Не указан"},
}


def t(key: str, locale: ReportLocale) -> str:
    """Lookup строки. KeyError если ключа нет — лучше fail-fast в render."""
    entry = _STRINGS[key]
    return entry[locale]


def event_label(event_type: str, locale: ReportLocale, *, custom_type: str | None = None) -> str:
    """Человеко-читаемый ярлык для GEDCOM event_type."""
    if event_type == "CUSTOM" and custom_type:
        return custom_type
    entry = _EVENT_LABELS.get(event_type)
    if entry is None:
        return event_type
    return entry[locale]


def sex_label(sex: str, locale: ReportLocale) -> str:
    """Sex enum → label. ``M`` / ``F`` / ``U`` (unknown) / ``X`` (intersex)."""
    mapping: dict[str, dict[ReportLocale, str]] = {
        "M": {"en": "Male", "ru": "Мужской"},
        "F": {"en": "Female", "ru": "Женский"},
        "U": {"en": "Unknown", "ru": "Не указан"},
        "X": {"en": "Other / intersex", "ru": "Другой / интерсекс"},
    }
    entry = mapping.get(sex)
    if entry is None:
        return t("unknown_sex", locale)
    return entry[locale]


def relation_label(kind: str, locale: ReportLocale) -> str:
    """RelationshipClaim.relation_kind → label."""
    mapping: dict[str, str] = {
        "parent": "relation_parent",
        "child": "relation_child",
        "spouse": "relation_spouse",
        "sibling": "relation_sibling",
    }
    return t(mapping[kind], locale)


def evidence_kind_label(kind: str, locale: ReportLocale) -> str:
    """EventClaim/RelationshipClaim evidence-type → label."""
    return t(f"kind_{kind}", locale)


def confidence_method_label(method: str, locale: ReportLocale) -> str:
    """ConfidenceMethod → label."""
    mapping: dict[str, str] = {
        "bayesian_fusion_v2": "method_bayesian",
        "naive_count": "method_naive",
        "asserted_only": "method_asserted",
    }
    return t(mapping[method], locale)


def scope_label(scope: str, target_gen: int | None, locale: ReportLocale) -> str:
    """Scope label с подстановкой target_gen, если применимо."""
    if scope == "ancestry_to_gen":
        template = t("scope_ancestry_to_gen", locale)
        return template.format(n=target_gen if target_gen is not None else "?")
    return t(f"scope_{scope}", locale)


def negative_kind_label(kind: str, locale: ReportLocale) -> str:
    """NegativeFinding.kind → label."""
    return t(f"negative_kind_{kind}", locale)


def coerce_locale(raw: str | None) -> ReportLocale:
    """Нормализация ``raw`` → допустимый locale, иначе ``en``.

    Используется когда locale приходит из request body — Pydantic-валидация
    уже обработала, но даём явный helper для не-API call-site'ов (jobs).
    """
    if raw in ("en", "ru"):
        return cast("Literal['en', 'ru']", raw)
    return "en"


__all__ = [
    "coerce_locale",
    "confidence_method_label",
    "event_label",
    "evidence_kind_label",
    "negative_kind_label",
    "relation_label",
    "scope_label",
    "sex_label",
    "t",
]
